GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/products/15634

###

POST http://localhost:3000/api/products
Content-Type: application/json

 {"id": "", "model": "samsung s8", "type": "phone", "price": "4790"}
###

//PUT 
PUT http://localhost:3000/api/products/71
Content-Type: application/json

{"price": "6000"}

###

//DELETE
DELETE http://localhost:3000/api/products/330713

###